'use strict';

export const SHOW_DESCRIPTORIZER = 'SHOW_DESCRIPTORIZER';
export const SET_DESCRIPTORIZER_CARDS = 'SET_DESCRIPTORIZER_CARDS';

export const CHOOSERATER = 'CHOOSERATER';
export const COMPARE_TWO = 'COMPARE_TWO';
export const PICK_FIVE = 'PICK_FIVE';
